import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";
import { api } from "../../services/api";

const COLORS = ["#0a2b24", "#2e7a69", "#ea7f48", "#f4c96d", "#3b82a0", "#718096"];
const metricGroups = [
  { key: "people_benefited", label: "People reached", note: "documented benefit across impact records", accent: "gold" },
  { key: "problems_completed", label: "Challenges completed", note: "problems moved through the full workflow", accent: "teal" },
  { key: "solutions_deployed", label: "Solutions deployed", note: "solutions marked ready or in implementation", accent: "clay" },
  { key: "districts_covered", label: "Districts covered", note: "communities represented in the network", accent: "teal" },
  { key: "universities_involved", label: "Universities involved", note: "research institutions in the platform", accent: "gold" },
  { key: "industry_partners", label: "Industry partners", note: "technology and delivery contributors", accent: "clay" },
  { key: "projects_completed", label: "Projects completed", note: "structured pilots with milestones", accent: "teal" },
  { key: "technologies_transferred", label: "Technologies transferred", note: "tools moved toward public use", accent: "gold" },
];

export default function ImpactPage() {
  const [data, setData] = useState(null);
  const [analytics, setAnalytics] = useState(null);
  const [storyFilter, setStoryFilter] = useState("all");
  const [err, setErr] = useState("");
  useEffect(() => {
    Promise.all([api("/api/impact"), api("/api/analytics")]).then(([impact, summary]) => { setData(impact); setAnalytics(summary); }).catch((error) => setErr(error.message));
  }, []);
  const stories = useMemo(() => (data?.stories || []).filter((story) => storyFilter === "all" || (storyFilter === "verified" ? story.verified : story.is_demo)), [data, storyFilter]);
  if (!data && !err) return <div className="section-shell py-24"><div className="h-10 w-64 animate-pulse rounded bg-emerald-100" /><div className="mt-6 h-24 rounded-2xl bg-white" /></div>;
  return <div className="pb-20">
    <section className="hero-grid text-white"><div className="section-shell py-16 md:py-20"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-gold">Public outcomes dashboard</p><h1 className="mt-4 font-serif text-4xl leading-tight md:text-6xl">See the distance between a challenge and a change.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-emerald-50/80">Impact is built from traceable problem records, accountable decisions, research contributions and projects that move toward implementation.</p></div><div className="mt-8 flex flex-wrap gap-3 text-sm text-emerald-50/80"><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2">Live platform data</span><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2">Demo records clearly labelled</span><span className="rounded-full border border-white/15 bg-white/10 px-4 py-2">Government-led workflow</span></div></div></section>
    {err && <div className="section-shell pt-6"><p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">Unable to load the latest impact data: {err}</p></div>}
    {data && <>
      <section className="section-shell -mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metricGroups.slice(0, 4).map((metric) => <MetricCard key={metric.key} metric={metric} value={data[metric.key]} />)}</section>
      <section className="section-shell py-16"><div className="mb-8 max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-forest-600">Network scale</p><h2 className="mt-2 font-serif text-4xl text-forest-950">A shared system for public problem-solving.</h2><p className="mt-3 text-slate-600">The platform brings together the people and institutions needed to move from local evidence to useful action.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metricGroups.slice(4).map((metric) => <MetricCard key={metric.key} metric={metric} value={data[metric.key]} compact />)}</div></section>
      {analytics && <section className="section-shell"><div className="grid gap-5 lg:grid-cols-2"><ChartPanel title="Challenges by category" subtitle="Where communities are asking for help"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.category || []} margin={{ top: 10, right: 10, left: -18, bottom: 0 }}><XAxis dataKey="name" hide /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#2e7a69" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel><ChartPanel title="Challenges by district" subtitle="The geographic reach of reported problems"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.district || []} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={3}>{(analytics.district || []).map((item, index) => <Cell key={item.name} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></ChartPanel></div></section>}
      <section className="section-shell pt-16"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-forest-600">Evidence stories</p><h2 className="mt-2 font-serif text-4xl text-forest-950">What changed, and how we know.</h2></div><div className="flex rounded-xl bg-white p-1 shadow-sm ring-1 ring-slate-200"><button type="button" onClick={() => setStoryFilter("all")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${storyFilter === "all" ? "bg-forest-800 text-white" : "text-slate-500"}`}>All stories</button><button type="button" onClick={() => setStoryFilter("verified")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${storyFilter === "verified" ? "bg-forest-800 text-white" : "text-slate-500"}`}>Verified</button><button type="button" onClick={() => setStoryFilter("demo")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${storyFilter === "demo" ? "bg-forest-800 text-white" : "text-slate-500"}`}>Demo</button></div></div><div className="grid gap-5 md:grid-cols-2">{stories.map((story) => <StoryCard key={story.id} story={story} />)}{stories.length === 0 && <div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No stories match this filter yet.</div>}</div></section>
      <section className="section-shell pt-16"><div className="rounded-[28px] bg-forest-950 p-7 text-white md:p-10"><div className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-gold">Continue the chain</p><h2 className="mt-3 max-w-2xl font-serif text-3xl md:text-4xl">Every strong outcome starts with a problem worth making visible.</h2><p className="mt-4 max-w-xl leading-7 text-emerald-50/75">Submit a local challenge, explore the public record, or join the network with research and delivery capacity.</p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link to="/problems" className="rounded-xl bg-clay px-4 py-3 text-sm font-semibold text-white">Explore problems</Link><Link to="/register" className="rounded-xl border border-white/20 px-4 py-3 text-sm font-semibold text-white">Join the network</Link></div></div></div></section>
    </>}
  </div>;
}

function MetricCard({ metric, value, compact }) { const color = metric.accent === "gold" ? "bg-gold" : metric.accent === "clay" ? "bg-clay" : "bg-teal-500"; return <div className={`rounded-2xl border border-slate-200 bg-white shadow-soft ${compact ? "p-5" : "p-6"}`}><div className={`mb-5 h-2 w-12 rounded-full ${color}`} /><p className={`${compact ? "text-3xl" : "text-4xl"} font-serif text-forest-950`}>{Number(value || 0).toLocaleString()}</p><p className="mt-2 font-semibold text-slate-800">{metric.label}</p><p className="mt-2 text-sm leading-6 text-slate-500">{metric.note}</p></div>; }
function ChartPanel({ title, subtitle, children }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><h3 className="font-serif text-2xl text-forest-950">{title}</h3><p className="mt-1 text-sm text-slate-500">{subtitle}</p><div className="mt-4 h-72">{children}</div></div>; }
function StoryCard({ story }) { return <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><div className="flex flex-wrap items-center justify-between gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${story.verified ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{story.verified ? "Verified metric" : "DEMO DATA"}</span><span className="text-xs text-slate-400">{Number(story.people_benefited || 0).toLocaleString()} people recorded</span></div><div className="mt-6 space-y-4"><StoryLine label="Before" text={story.before} /><StoryLine label="Intervention" text={story.solution} /><StoryLine label="After" text={story.after} /></div></article>; }
function StoryLine({ label, text }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-forest-600">{label}</p><p className="mt-1 text-sm leading-6 text-slate-600">{text}</p></div>; }
